name: Daily Menu Scraper

on:
  schedule:
    - cron: '52 7 * * 1-5'  # 9:52 AM EET (10:52 AM EEST, 7:52 AM UTC), Monday-Friday
  workflow_dispatch:  # Allow manual trigger

jobs:
  scrape-menu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install production dependencies only
        run: yarn install --production
        
      - name: Download latest build artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          name: built-app
          path: dist/
          workflow: build.yml
          workflow_conclusion: success
        
      - name: Run scraper script
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        run: ./scrape.sh
        
      - name: Get current date
        id: date
        run: echo "date=$(date +%Y-%m-%d)" >> $GITHUB_OUTPUT
        
      - name: Commit results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add db/*.json merged.json
          git commit -m "Menu data for ${{ steps.date.outputs.date }}" || exit 0
          git push

permissions:
  contents: write  # Required to push data commits
  actions: read     # Required to download artifacts 